### PR TITLE
#11 weekly overview ui and changeable current day

### PR DESCRIPTION
**Pull request by hklebs**

### CODE REVIEW

**Comment by EdHurtig** [comment]
image

**Comment by EdHurtig** [comment]
I think this looks pretty good so far.  Handing back to you @hklebs

**Comment by ColinKohler** [comment]
Looking good. The Week selector is probably a little to large. Can you also remove the app/app.iml file so no ones settings get bungled

**Comment by EdHurtig** [comment]
```
echo '.idea/' >> .gitignore
git rm --cached .idea/
```

**Pull request merged**
