### PR TITLE
Attempting to save changes to database

### PR DESCRIPTION
**Pull request by ColinKohler**

### CODE REVIEW

**Comment by EdHurtig** [comment]
will check this out and look

**Comment by EdHurtig** [comment]
I'm not able to load the preferences activity... so I am not even getting to the point of where the HTTP request is executed

**Comment by ColinKohler** [comment]
Are you getting a error. This all worked fine for me?

**Comment by EdHurtig** [comment]
Yeah the typical android level "app has stopped working" error.  Not sure what's up with that

**Comment by ColinKohler** [comment]
Huh... Thats useless. None of my changes should have caused that error of all things...

**Comment by EdHurtig** [comment]
let me check on master where you forked from... 271a78d194ae6addb93e9921534549969408a7bd

**Comment by EdHurtig** [comment]
@ColinKohler It's broked before this PR

**Comment by ColinKohler** [comment]
does reverting to here fix it: fed3d27?

**Comment by EdHurtig** [comment]
not sure how it would... got appt right now... can you check this out to find where it broke?

**Comment by ColinKohler** [comment]
Yea, I'll check when I get out of lab but I dunno if I'll be able to tell cause everything worked fine for me last night...

**Comment by ColinKohler** [comment]
Okay I fixed that crash.

**Pull request merged**
